name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test
      MAVEN_OPTS: -Dmaven.test.failure.ignore=false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Make Maven Wrapper executable (optional)
        run: if [ -f ./mvnw ]; then chmod +x mvnw; fi

      - name: Verify (checkstyle + tests)
        run: |
          if [ -f ./mvnw ]; then
            ./mvnw -B -ntp clean verify
          else
            mvn -B -ntp clean verify
          fi

      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/*.txt
            **/target/surefire-reports/*.xml

  package:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Package
        run: |
          if [ -f ./mvnw ]; then
            ./mvnw -B -ntp -DskipTests package
          else
            mvn -B -ntp -DskipTests package
          fi

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
